security:

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      id: App\User\Application\Provider\UserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      stateless: true
      logout: ~
      guard:
        authenticators:
          - App\Core\Infrastructure\Container\Application\Service\TokenAuthenticator

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Note: Only the *first* access control that matches will be used
  access_control:
    # Company
    - { path: '/api/v1/companies/mother', roles: [ROLE_ADMIN], methods: [GET] }
    - { path: '/api/v1/companies/\d+', roles: [ROLE_ADMIN], methods: [GET, PUT] }
    - { path: '/api/v1/companies', roles: [ROLE_ADMIN], methods: [GET, POST] }
    - { path: '/api/v1/companies/\d+/section', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT],methods: [GET] }
    - { path: '/api/v1/sections', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT,ROLE_ADMIN], methods: [GET] }

    # Wiki
    - { path: '/api/v1/companies/\d+/articles', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [GET] }
    - { path: '/api/v1/companies/\d+/articles/\d+', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [GET, PUT, DELETE ] }
    - { path: '/api/v1/companies/\d+/categories', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [GET] }
    - { path: '/api/v1/articles', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [POST] }

    # User
    - { path: '/api/v1/users/manager-client', roles: [ROLE_ADMIN], methods: [GET] }
    - { path: '/api/v1/users/manager-support', roles: [ROLE_ADMIN], methods: [GET] }
    - { path: '/api/v1/users/client', roles: [ROLE_MANAGER_CLIENT, ROLE_MANAGER_SUPPORT], methods: [GET] }
    - { path: '/api/v1/users/support', roles: [ROLE_MANAGER_CLIENT, ROLE_MANAGER_SUPPORT], methods: [GET] }
    - { path: '/api/v1/users', roles: [ROLE_MANAGER_CLIENT, ROLE_MANAGER_SUPPORT, ROLE_ADMIN], methods: [POST] }
    - { path: '/api/v1/users/\d+', roles: [ROLE_SUPPORT, ROLE_CLIENT, ROLE_MANAGER_CLIENT, ROLE_MANAGER_SUPPORT, ROLE_ADMIN], methods: [GET, PUT] }
    - { path: '/api/v1/users/\d+/image', roles: [ROLE_SUPPORT, ROLE_CLIENT, ROLE_MANAGER_CLIENT,ROLE_MANAGER_SUPPORT, ROLE_ADMIN], methods: [POST] }

    # Attendance
    - { path: '/api/v1/requests', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT], methods: [POST] }
    - { path: '/api/v1/requests', roles: [ROLE_SUPPORT, ROLE_CLIENT, ROLE_MANAGER_CLIENT,ROLE_MANAGER_SUPPORT], methods: [GET] }
    - { path: '/api/v1/requests/\d+', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT], methods: [PUT] } ## esta rota tem que apagar
    - { path: '/api/v1/requests/\d+', roles: [ROLE_SUPPORT, ROLE_CLIENT, ROLE_MANAGER_CLIENT,ROLE_MANAGER_SUPPORT]], methods: [GET] }
    - { path: '/api/v1/requests/move/\d+/in-attendance', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [POST] }
    - { path: '/api/v1/requests/move/\d+/canceled', roles: [ROLE_MANAGER_SUPPORT], methods: [POST] }
    - { path: '/api/v1/requests/\d+/transfer-company', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [POST] }
    - { path: '/api/v1/requests/\d+/submit-for-approval', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [POST] }
    - { path: '/api/v1/requests/export-requests-to-pdf', roles: [ROLE_MANAGER_SUPPORT, ROLE_MANAGER_CLIENT], methods: [GET] }
    - { path: '/api/v1/requests/\d+/approve', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT], methods: [POST] }
    - { path: '/api/v1/requests/move/\d+/awaiting-response', roles: [ROLE_SUPPORT, ROLE_MANAGER_SUPPORT], methods: [POST] }
    - { path: '/api/v1/requests/\d+/answered-request', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT], methods: [POST] }
    - { path: '/api/v1/requests/\d+/disapprove', roles: [ROLE_CLIENT, ROLE_MANAGER_CLIENT], methods: [POST] }
