alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET

get_all_companies:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\FindAllCompaniesAction
  methods:    GET

get_company_by_id:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\FindCompanyByIdAction
  methods:    GET|HEAD
  requirements:
    id: '\d+'

create_company:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\CreateCompanyAction
  methods:    POST

update_company:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\UpdateCompanyAction
  methods:    PUT
  requirements:
    id: '\d+'

get_mother_company:
  path: /api/v1/companies/mother
  controller: App\Company\Presentation\Http\Action\FindMotherCompanyAction
  methods:    GET

get_all_slas:
  path: /api/v1/slas
  controller: App\Company\Presentation\Http\Action\FindAllSLAAction
  methods:    GET

update_sla:
  path: /api/v1/slas/{id}
  controller: App\Company\Presentation\Http\Action\UpdateSLAAction
  methods:    PUT
  requirements:
    id: '\d+'