alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET

list_companies:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\ListCompaniesAction
  methods:    GET

create_company:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\CreateCompanyAction
  methods:    POST