alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET

login:
  path: /login
  controller: App\Security\Presentation\Http\Action\LoginAction
  methods:    POST

get_all_companies:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\FindAllCompaniesAction
  methods:    GET

get_company_by_id:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\FindCompanyByIdAction
  methods:    GET|HEAD
  requirements:
    id: '\d+'

create_company:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\CreateCompanyAction
  methods:    POST

update_company:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\UpdateCompanyAction
  methods:    PUT
  requirements:
    id: '\d+'

get_mother_company:
  path: /api/v1/companies/mother
  controller: App\Company\Presentation\Http\Action\FindMotherCompanyAction
  methods:    GET

get_all_sections:
  path: /api/v1/sections
  controller: App\Company\Presentation\Http\Action\FindAllSectionsAction
  methods:    GET

update_section:
  path: /api/v1/sections/{id}
  controller: App\Company\Presentation\Http\Action\UpdateSectionAction
  methods:    PUT

## =============== Wiki routes

get_all_articles_from_company:
  path: /api/v1/companies/{id}/articles
  controller: App\Wiki\Presentation\Http\Action\FindAllArticlesFromCompanyAction
  methods:    GET

get_article_by_id:
  path: /api/v1/companies/{idCompany}/articles/{idArticle}
  controller: App\Wiki\Presentation\Http\Action\FindArticlesByIdAction
  methods:    GET
  requirements:
    id: '\d+'

create_article:
  path: /api/v1/articles
  controller: App\Wiki\Presentation\Http\Action\CreateArticleAction
  methods:    POST

update_article:
  path: /api/v1/companies/{idCompany}/articles/{idArticle}
  controller: App\Wiki\Presentation\Http\Action\UpdateArticleAction
  methods:    PUT
  requirements:
    id: '\d+'

delete_article:
  path: /api/v1/articles/{id}
  controller: App\Wiki\Presentation\Http\Action\DeleteArticleAction
  methods:    DELETE
  requirements:
    id: '\d+'

get_all_categories:
  path: /api/v1/companies/{id}/categories/
  controller: App\Wiki\Presentation\Http\Action\FindAllCategoriesFromCompanyAction
  methods:    GET

update_category:
  path: /api/v1/companies/{idCompany}/categories/{idCategory}
  controller: App\Wiki\Presentation\Http\Action\UpdateCategoryAction
  methods:    PUT
  requirements:
    id: '\d+'

## =============== Wiki routes