alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET

login:
  path: /login
  controller: App\Security\Presentation\Http\Action\LoginAction
  methods:    POST

get_all_companies:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\FindAllCompaniesAction
  methods:    GET

get_company_by_id:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\FindCompanyByIdAction
  methods:    GET|HEAD
  requirements:
    id: '\d+'

create_company:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\CreateCompanyAction
  methods:    POST

update_company:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\UpdateCompanyAction
  methods:    PUT
  requirements:
    id: '\d+'

get_mother_company:
  path: /api/v1/companies/mother
  controller: App\Company\Presentation\Http\Action\FindMotherCompanyAction
  methods:    GET

get_all_sections:
  path: /api/v1/sections
  controller: App\Company\Presentation\Http\Action\FindAllSectionsAction
  methods:    GET
  
update_section:
  path: /api/v1/sections/{id}
  controller: App\Company\Presentation\Http\Action\UpdateSectionAction
  methods:    PUT

get_all_articles_from_company:
  path: /api/v1/companies/{id}/wiki
  controller: App\Wiki\Presentation\Http\Action\FindAllArticleFromCompanyAction
  methods:    GET
