alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET

list_companies:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\ListCompaniesAction
  methods:    GET

get_company_by_id:
  path: /api/v1/companies/{id}
  controller: App\Company\Presentation\Http\Action\CompanyByIdAction
  methods:    GET|HEAD
  requirements:
    id: '\d+'

create_company:
  path: /api/v1/companies
  controller: App\Company\Presentation\Http\Action\CreateCompanyAction
  methods:    POST