list_posts:
  path: /posts/{id}
  controller: App\Blog\Presentation\Http\Action\ListPostAction
  methods:    GET
  requirements:
      id: '\d+'

alive:
  path: /alive
  controller: App\Core\Presentation\Http\Action\AliveAction
  methods:    GET